### ISSUE TITLE
Grove-Servo

### ISSUE THREAD

**Issue by bartimau** [1ft-seabass/node-red-contrib-grove-base-hat#1]
Hi!
We are working recently with your nodes! They work perfeclty fine. 

We saw you are planing to publish the grove-servo node. We tryed to implement it but we failed poorly. 

Are you having a date when you are planning to publish this node? Otherwise any hints what would be the next steps to implement it? 

Greatings!

**Comment by 1ft-seabass** [comment]
Thank you for trying my node!
As you know, these nodes bridges node.js to python based grove.py. Actually I noticed that this grove-servo node used grove_servo.py is a little not easy maybe.
I'm going to research and check it in a detail recently in this late Jan to Feb. Can you wait for that period?

**Comment by bartimau** [comment]
Thank you for this fast response! 

This sounds amazing and would help our project a lot! It really would be great if we could use the node until end of february so it fits in the schedual. 

We are looking forward for your node on this topic and thank you for helping us out!

**Comment by 1ft-seabass** [comment]
@bartimau Hi! I updated to v0.0.8 for adding grove-servo node. I know that this node using PWM port is sure now. You would use its port please.
In addtion, I tell just in case. Grove Servo requires enough voltage. So I recommend that you try using single servo usecase in first step. Actually I also check it successfully.

**Comment by 1ft-seabass** [comment]
@bartimau Hi. I will close the issue. Because I already made the grove-servo node. Surely I can see that it is working confortably. :)

I enjoyed to disscuss here with you. Thank you for your report.

Regards,
Seigo
