### ISSUE TITLE
Command failed on LED Node

### ISSUE THREAD

**Issue by 1ft-seabass** [1ft-seabass/node-red-contrib-grove-base-hat#2]
I moved. Thanks @StevenRott .

https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/commit/ca9d861e5932cc2c5c55e21f1d469b850f80c50d#commitcomment-37716900

> Hello,
> first of all, thanks for your great Nodes for the Grove Base Hat. I have a problem by developping my flows like this:
> I have a GroveBaseHat on a Raspberry Pi 3 with different Sensors from Seeed. I want to make some Nodes with Node-Red. But if I deploy my Node with i.e. one LED an a inject of "0" or "1" the Node-Red turn back a mistake like this:
> 
> ```
> 8 Mar 13:41:25 - [info] Flows starten
> 8 Mar 13:41:25 - [info] Flows gestartet
> 8 Mar 13:41:47 - [info] Flows stoppen
> 8 Mar 13:41:47 - [info] Flows gestoppt
> 8 Mar 13:41:47 - [info] Flows starten
> 8 Mar 13:41:47 - [info] Flows gestartet
> { Error: Command failed: python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1
> at ChildProcess.exithandler (child_process.js:273:12)
> at ChildProcess.emit (events.js:180:13)
> at maybeClose (internal/child_process.js:936:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> killed: false,
> code: 2,
> signal: null,
> cmd: 'python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1' }
> What can i do.....???
> ```
> 
> Sorry for my bad english......
> 
> Is this problem fixed with this new JSON-package ???
> 
> Greets Steven

**Comment by StevenRott** [comment]
Hi,

i have this problem although, when I deploy a Node with the SHT11 temeprature ans humidity sensor or with a servo Motor etc.....don't know why ??

Greets an thanks for your help,

Steven

**Comment by 1ft-seabass** [comment]
Hi @StevenRott,
I confirmed your report on LED node. But I succeeded to work the node of latest version and LED sample node.

I have a question about [README.md](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat) . Do you already succeeded "0. Setup Grove Base HAT"?

Seigo

**Comment by StevenRott** [comment]
Hi Seigo,

i have installed Grove BAse Hat with the online installation and get the follwoing meesage:

> Installing collected packages: grove.py
 

>  Found existing installation: grove.py 0.6
>     Uninstalling grove.py-0.6:
>       Successfully uninstalled grove.py-0.6
>   Running setup.py install for grove.py ... done
> Successfully installed grove.py-0.6
> Collecting https://github.com/Seeed-Studio/grove.py/archive/master.zip
>   Using cached https://github.com/Seeed-Studio/grove.py/archive/master.zip
> Requirement already up-to-date: RPi.GPIO in /usr/local/lib/python3.5/dist-packages (from grove.py==0.6)
> Requirement already up-to-date: rpi_ws281x in /usr/local/lib/python3.5/dist-packages (from grove.py==0.6)
> Requirement already up-to-date: smbus2 in /usr/local/lib/python3.5/dist-packages (from grove.py==0.6)
> Installing collected packages: grove.py
>   Found existing installation: grove.py 0.6
>     Uninstalling grove.py-0.6:
>       Successfully uninstalled grove.py-0.6
>   Running setup.py install for grove.py ... done
> Successfully installed grove.py-0.6
> #######################################################
>   Lastest Grove.py from github install complete   !!!!!
> 
> > #######################################################
 

So I think everything is okay.....

After that I installed the Nodes for Grove with the following:

> npm install node-red-contrib-grove-base-hat

Then I get this:

> npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
> npm WARN pi No description
> npm WARN pi No repository field.
> npm WARN pi No README data
> npm WARN pi No license field.
> 
> + node-red-contrib-grove-base-hat@0.0.9
> updated 1 package and audited 3 packages in 3.649s
> found 0 vulnerabilities

Is here everything okay ?????

Now, I started Update of Node-Red with update-nodejs-and-nodered, I get the following:

> Holen:1 http://deb.nodesource.com/node_9.x stretch InRelease [4.623 B]
> OK:2 http://archive.raspberrypi.org/debian stretch InRelease                   
> OK:3 http://raspbian.raspberrypi.org/raspbian stretch InRelease                
> OK:4 https://seeed-studio.github.io/pi_repo stretch InRelease                  
> Es wurden 4.623 B in 1 s geholt (2.348 B/s).
> Paketlisten werden gelesen... Fertig
> Paketlisten werden gelesen...
> Abhängigkeitsbaum wird aufgebaut....
> Statusinformationen werden eingelesen....
> nodejs ist schon die neueste Version (9.11.2-1nodesource1).
> nodered ist schon die neueste Version (0.20.7-0).
> Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
> Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
> Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
> nicht erstellt wurden oder Incoming noch nicht verlassen haben.
> Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:
> 
> Die folgenden Pakete haben unerfüllte Abhängigkeiten:
>  nodejs : Kollidiert mit: npm
> E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
> 
> npm now version 6.14.2

The I Started Node-Red with note-red-start and I started the instance in my browser under 192.168.1.35:1880:

> Start Node-RED
>  
> Once Node-RED has started, point a browser at http://192.168.1.35:1880
> On Pi Node-RED works better with the Firefox or Chrome browser
>  
> Use   node-red-stop                          to stop Node-RED
> Use   node-red-start                         to start Node-RED again
> Use   node-red-log                           to view the recent log output
> Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
> Use   sudo systemctl disable nodered.service to disable autostart on boot
>  
> To find more nodes and example flows - go to http://flows.nodered.org
>  
> Starting as a systemd service.
> Started Node-RED graphical event wiring tool.
> 9 Mar 15:12:11 - [info]
> Willkommen bei Node-RED!
> ===================
> 9 Mar 15:12:11 - [info] Node-RED Version: v0.20.7
> 9 Mar 15:12:11 - [info] Node.js  Version: v9.11.2
> 9 Mar 15:12:11 - [info] Linux 4.19.66-v7+ arm LE
> 9 Mar 15:12:12 - [info] Paletten-Nodes werden geladen
> 9 Mar 15:12:20 - [warn] ------------------------------------------------------
> 9 Mar 15:12:20 - [warn] [node-red-node-serialport/serialport] Error: The module '/usr/lib/node_modules/node-red-node-serialport/node_modules/@serialport/bindings/build/Release/bindings.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 57. This version of Node.js requires
> NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).
> 9 Mar 15:12:20 - [warn] [node-red-contrib-grove-base-hat/grove-rgb-led-ws2813-mini] Error: /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-rgb-led-ws2813-mini/grove-rgb-led-ws2813-mini.html does not exist
> 9 Mar 15:12:20 - [warn] ------------------------------------------------------
> 9 Mar 15:12:20 - [info] Einstellungsdatei: /home/pi/.node-red/settings.js
> 9 Mar 15:12:20 - [info] Kontextspeicher: 'default' [ module=memory]
> 9 Mar 15:12:20 - [info] Benutzerverzeichnis: /home/pi/.node-red
> 9 Mar 15:12:20 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
> 9 Mar 15:12:20 - [info] Flow-Datei: /home/pi/.node-red/flows_dex.json
> 9 Mar 15:12:20 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgefÃ¼hrt.
> 9 Mar 15:12:20 - [warn]
> ---------------------------------------------------------------------
> Die Datei mit den Datenflowberechtigungsnachweisen wird mit einem vom System generierten SchlÃ¼ssel verschlÃ¼sselt.
> Wenn der vom System generierte SchlÃ¼ssel aus irgendeinem Grund verloren geht, werden Ihre Berechtigungsnachweise
> Die Datei kann nicht wiederhergestellt werden. Sie mÃ¼ssen sie lÃ¶schen und erneut eingeben.
> Ihre Berechtigungsnachweise.
> Sie sollten Ihren eigenen SchlÃ¼ssel mit Hilfe der Option 'credentialSecret' in
> Ihre Einstellungsdatei. Node-RED wird dann Ihre Berechtigungsnachweise erneut verschlÃ¼sseln.
> Datei mit dem ausgewÃ¤hlten SchlÃ¼ssel beim nÃ¤chsten Deployen einer Ãnderung verwenden.
> ---------------------------------------------------------------------
> 9 Mar 15:12:20 - [info] Flows starten
> 9 Mar 15:12:20 - [info] Flows gestartet

I deployed my flow with an inject (Number 1) and a grove-led and get the following:

> { Error: Command failed: python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1
>     at ChildProcess.exithandler (child_process.js:273:12)
>     at ChildProcess.emit (events.js:180:13)
>     at maybeClose (internal/child_process.js:936:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
>   killed: false,
>   code: 2,
>   signal: null,
>   cmd: 'python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1' }

Whats wrong ???? I don't understand it !!! Can you help me please ???

Greets Steven

**Comment by StevenRott** [comment]
SO can I plug the sensors without turn off the Raspi ??

**Comment by 1ft-seabass** [comment]
Hello, Steven
Thank you for your response!

> Installing collected packages: grove.py

I see your grove.py installing log. I think also okay. Thanks.

> { Error: Command failed: python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1
at ChildProcess.exithandler (child_process.js:273:12)
at ChildProcess.emit (events.js:180:13)
at maybeClose (internal/child_process.js:936:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
killed: false,
code: 2,
signal: null,
cmd: 'python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1' }

> npm install node-red-contrib-grove-base-hat
> npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'

Next I recognized '/home/pi/package.json' log. if 'npm install node-red-contrib-grove-base-hat' command run '/home/pi/.node-red/' as Node-RED setting directory, this log will output '/home/pi/.node-red/'.
This '/home/pi/' log outputs that you probably have installed this node '/home/pi/' directory in current. In this case it is not work.

So you should install this node on '/home/pi/.node-red/'. Could you add this node on the palette? This detail of operation is https://nodered.org/docs/user-guide/runtime/adding-nodes .

Warmly
Seigo

**Comment by StevenRott** [comment]
I installed it although with the palette !! Nothing else !!! :-( How can i deinstall all the components ? Can you help me ??
First i want deinstall your nodes, then Node-Red, then the grovebase Hat.....and then reinstall it.....perhaps it works !!!

**Comment by 1ft-seabass** [comment]
Oh... Thank you for your reporting the situation!

I think in thought that other installed softwares might have it effect maybe.

I'd like to understand your situation. So I also install cleanly. I can prepare Raspberry Pi 3B+ , SD card 16GB and Raspbian image (Release date: 2020-02-13)  late today. Sorry, I don't have Raspberry Pi 3B like you.

I will share the this flow. Could you wait for about a day?

**Comment by StevenRott** [comment]
Hi Seigo,

thank you for your response........

So I should install the Raspbian image again from the beginning ?! Can u help me by installing it step by step ? Where do u download the image? Can u send me the link ?!
And then step by step your commands to install the Grove Base Hat and Node Red and your nodes for the grovebase hat......can u send me this to...:-)))
Can i plug the Grove Base Hat on the Raspi from the beginning or when should I plug it ?!

SO we would have the same environment.......I thank you for all !! It's a great help for me !!!

Greets Steven

**Comment by 1ft-seabass** [comment]
Hello Steven, Thank for your response.

Actually I finished that clean install check at hand. and it is working successfully. I made the wiki page about this detail flow. and I share it to you just now :) It's helpful for you?

https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/wiki/The-one-of-installation-example-as-of-2020-03-10

Of course, your situations might be some differences to me. So I'd like to compare this link to your situations in moderation.

**Comment by StevenRott** [comment]
Hi Sergo,

thanks for your great installationscript......but I get the same mistake..... :-(
I have followed all your steps......
Is it a problem, that i enabled I2C, because i have a  temperature and humidity sensor ?? Here is the console and a photo !!! Can u help me ??? :-(( Sorry for all.....

**Comment by StevenRott** [comment]
> > pi@raspberrypi:~ $ grove_led 5
> Check whether I2C enabled and   Grove Base Hat RPi  or  Grove Base Hat RPi Zero  inserted
> pi@raspberrypi:~ $ grove_led 5
> Check whether I2C enabled and   Grove Base Hat RPi  or  Grove Base Hat RPi Zero  inserted
> pi@raspberrypi:~ $ node-red-start
> 
> Start Node-RED
>  
> Once Node-RED has started, point a browser at http://192.168.1.40:1880
> On Pi Node-RED works better with the Firefox or Chrome browser
>  
> Use   node-red-stop                          to stop Node-RED
> Use   node-red-start                         to start Node-RED again
> Use   node-red-log                           to view the recent log output
> Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
> Use   sudo systemctl disable nodered.service to disable autostart on boot
>  
> To find more nodes and example flows - go to http://flows.nodered.org
>  
> Starting as a systemd service.
> 11 Mar 18:28:50 - [info]
> Willkommen bei Node-RED!
> ===================
> 11 Mar 18:28:50 - [info] Node-RED Version: v1.0.4
> 11 Mar 18:28:50 - [info] Node.js  Version: v12.16.1
> 11 Mar 18:28:50 - [info] Linux 4.19.97-v7+ arm LE
> 11 Mar 18:28:52 - [info] Paletten-Nodes werden geladen
> 11 Mar 18:28:57 - [info] Einstellungsdatei: /home/pi/.node-red/settings.js
> 11 Mar 18:28:57 - [info] Kontextspeicher: 'default' [ module=memory]
> 11 Mar 18:28:57 - [info] Benutzerverzeichnis: /home/pi/.node-red
> 11 Mar 18:28:57 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
> 11 Mar 18:28:57 - [info] Flow-Datei: /home/pi/.node-red/flows_raspberrypi.json
> 11 Mar 18:28:57 - [info] Neue flow-Datei wird erstellt
> 11 Mar 18:28:57 - [warn]
> ---------------------------------------------------------------------
> Die Datei mit den Datenflowberechtigungsnachweisen wird mit einem vom System generierten Schlüssel verschlüsselt.
> Wenn der vom System generierte Schlüssel aus irgendeinem Grund verloren geht, werden Ihre Berechtigungsnachweise
> Die Datei kann nicht wiederhergestellt werden. Sie müssen sie löschen und erneut eingeben.
> Ihre Berechtigungsnachweise.
> Sie sollten Ihren eigenen Schlüssel mit Hilfe der Option 'credentialSecret' in
> Ihre Einstellungsdatei. Node-RED wird dann Ihre Berechtigungsnachweise erneut verschlüsseln.
> Datei mit dem ausgewählten Schlüssel beim nächsten Deployen einer Änderung verwenden.
> ---------------------------------------------------------------------
> 11 Mar 18:28:57 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt.
> 11 Mar 18:28:57 - [info] Flows starten
> 11 Mar 18:28:57 - [info] Flows gestartet
> 11 Mar 18:30:28 - [info] Modul wird installiert: node-red-contrib-grove-base-hat, Version: 0.0.9
> 11 Mar 18:30:37 - [info] Installiertes Modul: node-red-contrib-grove-base-hat
> 11 Mar 18:30:37 - [info] Hinzugefügte Node-Typen:
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-led
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-button
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-ultrasonic-ranger
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-light-sensor-v1_2
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-temperature-sensor
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-4-digit-display
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-relay
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-gesture-sensor
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-oled-display-128x64
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-i2c-color-sensor-v2
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-temperature-humidity-sensor-sht3x
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-magnetic-switch
> 11 Mar 18:30:37 - [info]  - node-red-contrib-grove-base-hat:grove-servo
> 11 Mar 18:31:26 - [info] Flows stoppen
> 11 Mar 18:31:26 - [info] Flows gestoppt
> 11 Mar 18:31:26 - [info] Flows starten
> 11 Mar 18:31:26 - [info] Flows gestartet
> Error: Command failed: python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:311:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   killed: false,
>   code: 2,
>   signal: null,
>   cmd: 'python -u /home/pi/.node-red/node_modules/node-red-contrib-grove-base-hat/grove-led/grove-led.py 5 1'
> }

**Comment by StevenRott** [comment]
![20200311_183619 1](https://user-images.githubusercontent.com/61965413/76446814-e6338800-63c7-11ea-87ab-5f0649072623.jpg)

**Comment by StevenRott** [comment]
![20200311_183631 1](https://user-images.githubusercontent.com/61965413/76446897-082d0a80-63c8-11ea-978f-a781c7609dc0.jpg)

**Comment by 1ft-seabass** [comment]
Thank you for trying my installationscript!

And my installationscript should said a single Grove LED case. Sorry I'm confused that you reached multiple connecting sensors suddenly.

I'd like to check **step by step** about this situation.

* At first, is my installationscript( a single Grove LED case ) working successfully?
  * In this case, I'm relieved that this node is working right basicly.

Could you tell me about the my installationscript( a single Grove LED case ) result? I'd like to separate some problems appropriately such as multiplue sensings and single LED working.

**Comment by StevenRott** [comment]
Hi Sergo
excuse me Form Thies....i thought i could plug immediately all Sensors.....but you're right....step by step!!! 😬
So, do i habe to reinstall everything?? From the beginning!?? Or is it possible to unplug all Sensors excluding the led and test it then!?? What makes Sensei!?? I habe to disable the i2c on the raspi!? Right!?
And another question.....can i plug Sensors during the raspi is on  or should i shutdown the raspi before i plug NEW Sensors!?
Great thanks Form your help!!!

**Comment by 1ft-seabass** [comment]
Hello Steven,

> And another question.....can i plug Sensors during the raspi is on or should i shutdown the raspi before i plug NEW Sensors!?

In current case, You should choose safer method. So shutdown your Raspberry Pi during you change new Grove sensor parts.

> I habe to disable the i2c on the raspi!? Right!?

No, you should **enable I2C** because my setting enabled it. I'd like to same setting for now.

My setting is like this. I2C setting is enabled.

![image](https://user-images.githubusercontent.com/2148840/76526066-51588980-64b0-11ea-8961-d5bd3c79a06f.png)

> So, do i habe to reinstall everything?? From the beginning!?? Or is it possible to unplug all Sensors excluding the led and test it then!??

You choose unpluging plan for now.

So,

* Shutdown your Raspberry Pi.
* Unplug all current sensors.
* Plug the Grove LED **only** in D5 port.
* Launch your Raspberry Pi.
* Try the headline of installationscript article at ["Check Grove Base Hat libraries."](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/wiki/The-one-of-installation-example-as-of-2020-03-10#check-grove-base-hat-libraries)
  * You will execute ```grove_led 5```

I hope that the LED is like this,

![image](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/raw/master/images/wiki/The-one-of-installation-example-as-of-2020-03-10/movie01.gif)

Regards,
Seigo

**Comment by StevenRott** [comment]
Hi Sergo,
so i've tested it....step by step.....
I unplugged all sensors, then i plug the Grove LED and started the Raspi.....with `grove_led 5`......everything works....the LED blinks !!
After that I shutdown the Raspi and plugged the Ultrasonic Sensor in D16......started the Raspi.....with `grove_ultrasonic_ranger 16`.....everything works......the msg.payload was the distance in cm !!
After that i shutdowned the Raspi and plugged the Servo in D18.....started Raspi......with `grove_servo 18` .....everything works....the servomotor turns from 0 till 180 degree and back......great.....
After that i shutdowned the Raspi and plugged the Temperature & Humidity Sensor......started the Raspi.....with `grove_temperature_humidity_sht31 i2c`.....i get the following mistake :-((((

> > pi@raspberrypi:~ $ grove_temperature_humidity_sht31 i2c
> Traceback (most recent call last):
>   File "/usr/local/bin/grove_temperature_humidity_sht31", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/grove/grove_temperature_humidity_sensor_sht3x.py", line 87, in main
>     temperature, humidity = sensor.read()
>   File "/usr/local/lib/python3.7/dist-packages/grove/grove_temperature_humidity_sensor_sht3x.py", line 59, in read
>     self.bus.write_i2c_block_data(self.address, 0x24, [0x00])
>   File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 622, in write_i2c_block_data
>     ioctl(self.fd, I2C_SMBUS, msg)
> OSError: [Errno 121] Remote I/O error

Whats wrong ??? I Have the folowing Grove Temeprature an Humidity Sensor.

Thanks for your help !!!

**Comment by StevenRott** [comment]
![20200312_204150](https://user-images.githubusercontent.com/61965413/76560873-69c1a780-64a2-11ea-8476-567b04419fd3.jpg)

**Comment by StevenRott** [comment]
![20200312_204209](https://user-images.githubusercontent.com/61965413/76560911-7d6d0e00-64a2-11ea-8d40-f31d8ca341f7.jpg)

**Comment by StevenRott** [comment]
![20200312_204215](https://user-images.githubusercontent.com/61965413/76561023-c02ee600-64a2-11ea-8947-cd6eaba2a62d.jpg)

**Comment by StevenRott** [comment]
When I shutdown the Raspi......and unplug the Temperature Sensor.....start the Raspi and give the command `grove_led 5` or `grove_ultrasonic_ranger 16` and so on.....everything works fine !!! What's wrong with the temperature sensor ?!

**Comment by 1ft-seabass** [comment]
Hi Steven,
Thank you for testing ```grove_led 5``` !

We shared a great situation! And I got a hint from your extra tests :)

Next I can check with you about the next step as Grove LED node. Because I heared that you get a trouble LED flow error first.

* Shutdown your Raspberry Pi.
* Plug the Grove LED only in D5 port.
* Launch your Raspberry Pi and Node-RED.
  * I guess that you install already node-red-contrib-grove-base-hat.
* Try ["Import the sample flow"](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/wiki/The-one-of-installation-example-as-of-2020-03-10#import-the-sample-flow) and ["Check the flow and Grove LED"](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/wiki/The-one-of-installation-example-as-of-2020-03-10#check-the-flow-and-grove-led).
* Is The Grove LED working also?

In this case success, we will shared this next situation about a general node-red-contrib-grove-base-hat working.

Of course, I wish also to go step up your nice report about Temperature & Humidity Sensor(TH02)! So I'd like remove other error possibility such as no working the node basicly before that.

If you check this, I can advice to you about next step :)

**Comment by StevenRott** [comment]
Hi Sergo, 
the GRove LED works fine with the sample node !! The other nodes like you see above works also fine.....so how can I get the temperature sensor working ?!:-)

Thaaks for your help !!

**Comment by StevenRott** [comment]
![grafik](https://user-images.githubusercontent.com/61965413/76594308-129af180-64f9-11ea-9f98-17f2ca084885.png)

**Comment by 1ft-seabass** [comment]
Thanks Steven,

I'm relieved about the responce such as grove-led, grove-ultrasonic, grove-servo!
Great, We have been reach the Temperature & Humidity Sensor(TH02) issue finally.

I already have summarized [Available Grove](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/blob/master/available_grove.md) page. Actually this page is linked from [README](https://github.com/1ft-seabass/node-red-contrib-grove-base-hat/blob/master/README.md) .

I explain the detail,

![image](https://user-images.githubusercontent.com/2148840/76595529-32550880-653f-11ea-8a2e-9f19f58f5625.png)

this node enables to work using [Temperature & Humidity Sensor (SHT31)](https://www.seeedstudio.com/Grove-Temperature-Humidity-Sensor-SHT3-p-2655.html) .

![image](https://user-images.githubusercontent.com/2148840/76595604-66c8c480-653f-11ea-8803-32d1c7b15e18.png)

this node enables to work using [Temperature Sensor](https://www.seeedstudio.com/Grove-Temperature-Sensor.html).

The node bridges from node-red Node.js to  [Python library for Seeedstudio Grove devices grove.py](https://github.com/Seeed-Studio/grove.py/tree/master/doc). So basically it follows the [grove.py](https://github.com/Seeed-Studio/grove.py/tree/master/doc) Available Grove.

So, Your TH02 sensor is the out of available sensor😥. Could you try to set the correct sensor (Temperature & Humidity Sensor (SHT31)) ?

Regards,
Seigo

**Comment by StevenRott** [comment]
Hi Sergo,

i purchased (hopefully) the correct Sensor....as soon as possible i will post my experience...:-)

Greets Steven

**Comment by StevenRott** [comment]
Another question:
Is it possible to plug another board on the Grove Base Hat like GrovePi+ oder WIO, or how can I use other sensors ???

**Comment by 1ft-seabass** [comment]
> Another question:
Is it possible to plug another board on the Grove Base Hat like GrovePi+ oder WIO, or how can I use other sensors ???

It's the out of support as the node basicly.

But I can comment as the one of IoT developer. If you choose this usecase, you should learn the knowledge for Grove Base Hat for Raspberry Pi itself. Try.

For example,
http://wiki.seeedstudio.com/Grove_Base_Hat_for_Raspberry_Pi/

**Comment by 1ft-seabass** [comment]
Hello Steven,
I'm pleasure to share to you about TH02 is the out of available sensor. :)

Of course, I understand that you would like to ask me about more questions for now. But generally GitHub issue page focus on "one issue page is one problem solving as much as possible".

Our status as this issue once again,

* [solved] Command failed on LED Node (this title of issue is same.)
* [waiting] Check only SHT31 sensor and SHT31 node.

We know that the issue already have tow problems like this. I'd like to keep it at least.

Warmly,
Seigo

**Comment by StevenRott** [comment]
Hi Sergo,

so i checked the new sensor.....everything works fine.....now I have to check it with a new flow in Node-Red.....i hope it's working......i'll give you the next response soon !:-)

So can i use the Grove_PWM_Buzzer with your nodes ???

Thanks for all,

Steven

**Comment by 1ft-seabass** [comment]
Hello, Steven,
Thank you for your checking about SHT31! I'm looking forward to the new flow using a single SHT31 flow. :)

> So can i use the Grove_PWM_Buzzer with your nodes ???

Sorry, my nodes still is not made about Grove_PWM_Buzzer. Actually I will make it in near future maybe.

**Comment by 1ft-seabass** [comment]
Hi Steven,

I have a few minutes. I try to execute the flow using node-red-contrib-grove-base-hat@0.0.9.

![image](https://user-images.githubusercontent.com/2148840/76818669-8450a380-6849-11ea-8a8c-1b357f4cf557.png)

And the flow data as JSON.

```js
[{"id":"cda1bf85.6a5d6","type":"inject","z":"a3099883.e8ed18","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":420,"wires":[["46c5d106.e7aff"]]},{"id":"46c5d106.e7aff","type":"grove-temperature-humidity-sensor-sht3x","z":"a3099883.e8ed18","name":"","x":500,"y":440,"wires":[["aa908c94.e3528"]]},{"id":"aa908c94.e3528","type":"debug","z":"a3099883.e8ed18","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":760,"y":460,"wires":[]}]
```

Then, I could get the SHT31 sensor datas like this.

![image](https://user-images.githubusercontent.com/2148840/76818759-c7ab1200-6849-11ea-9048-e4c1f5bf54f4.png)

I'm also looking forward your action. :)

All the best,
Seigo

**Comment by StevenRott** [comment]
Hi Seigo,

the flow works great !!! Thanks for your help !!!:-)

I think, we can close this issue !!

So, i would be very thankful, if you can develop the node for the Grove Buzzer !!:-))

All the best,

Steven

**Comment by 1ft-seabass** [comment]
Hi Steven,

I'm happy to solve with you! I'll think about Grove Buzzer node. :)

I'll close this issue.

Regards,
Seigo
