### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by VNXtreme** [1ft-seabass/node-red-contrib-grove-base-hat#5]
The updates for Grove-time-of-flight-distance and Grove-3-axis-digital-accelerometer sensor aren't available on NPM.
Can you please publish the new updates to NPM?

**Comment by 1ft-seabass** [comment]
Yes, I'm checking this node in my Paspberry Pi just now carefully. Please wait.

**Comment by 1ft-seabass** [comment]
I'm done!

* I published this version to npm using `npm publish`.
* I clicked `check for update` button at Node-RED node-red-contrib-grove-base-hat page.

Then this node was updated v 0.0.10. 👍 

Thank you for your code!
